#!/bin/bash

# Shopify Theme Development Helper
# This script helps you set up theme development

echo "🥤 Juice Bar Theme Development Helper"
echo "======================================"
echo ""

# Check current status
echo "🔍 Checking current setup..."
echo ""

# Check if we're authenticated
echo "📋 Available themes:"
npx @shopify/cli theme list --store=healthfood-juicebar100.myshopify.com 2>/dev/null || echo "❌ Not authenticated with Shopify"

echo ""
echo "🚀 Available development commands:"
echo "=================================="
echo ""
echo "1. 📱 Local Preview Server (WORKING)"
echo "   Command: npm run dev"
echo "   URL: http://localhost:9090"
echo "   Status: ✅ Currently running"
echo ""
echo "2. 🏪 Shopify Theme Dev (Needs store password)"
echo "   Command: npm run shopify:dev"
echo "   Status: ⚠️ Requires store password from Theme Access app"
echo ""
echo "3. 📤 Push to Development Theme"
echo "   Command: npm run shopify:push"
echo "   Status: ✅ Available"
echo ""
echo "4. 📥 Pull from Shopify"
echo "   Command: npm run shopify:pull"
echo "   Status: ✅ Available"
echo ""

echo "🎯 Quick Start Options:"
echo "======================"
echo ""
echo "Option A: Use Local Preview (Recommended for development)"
echo "  • Already running at http://localhost:9090"
echo "  • View theme structure and files"
echo "  • Fast development without Shopify connection"
echo "  • Perfect for design and layout work"
echo ""
echo "Option B: Connect to Shopify Theme Dev"
echo "  1. Go to your Shopify Admin"
echo "  2. Install 'Theme Access' app"
echo "  3. Generate a password for theme development"
echo "  4. Run: npm run shopify:dev --password=YOUR_PASSWORD"
echo ""
echo "Option C: Push changes to development theme"
echo "  • Edit theme files locally"
echo "  • Run: npm run shopify:push"
echo "  • Preview on your store's development theme"
echo ""

echo "🔗 Useful Links:"
echo "==============="
echo "• Local Preview: http://localhost:9090"
echo "• Store Admin: https://healthfood-juicebar100.myshopify.com/admin"
echo "• GitHub Repo: https://github.com/amo-tech-ai/juice-bar"
echo "• Theme Editor: https://healthfood-juicebar100.myshopify.com/admin/themes"
echo ""

echo "💡 Pro Tips:"
echo "============"
echo "• Use 'npm run dev' for fastest development"
echo "• Edit files in VS Code or your preferred editor"
echo "• Changes show immediately in local preview"
echo "• Use 'npm run shopify:push' to deploy changes"
echo "• Always test on multiple devices"
echo ""

echo "✅ Your theme is ready for development!"
echo "Choose your preferred development method and start coding! 🚀"
